name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # or your target version

    - name: Restore dependencies
      run: dotnet restore ./TestAppAlex/TestAppAlex.csproj

    - name: Build
      run: dotnet build ./TestAppAlex/TestAppAlex.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./TestAppAlex/TestAppAlex.csproj --configuration Release --output ./publish --no-build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-app
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: dotnet-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'se-lab-testapp-005-alex' # <- your Azure Web App name
        slot-name: 'production'
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
