# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: CD Pipeline - se-lab-testapp-005-alex

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore "${{ github.workspace }}/TestAppAlex/TestAppAlex.csproj"

      - name: Build project
        run: dotnet build "${{ github.workspace }}/TestAppAlex/TestAppAlex.csproj" --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish "${{ github.workspace }}/TestAppAlex/TestAppAlex.csproj" --configuration Release --output "${{ github.workspace }}/publish" --no-build

      - name: Upload published app
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{ github.workspace }}/publish"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5180BB95903C412AA80AE952DAB004DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CCBACDA2ABA42779FF2465240FDAE88 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20F2E7D507974D72924D90B4A31FE4C7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'se-lab-testapp-005-alex'
          slot-name: 'Production'
          package: .
